import type { Payload } from 'payload'

const TREE_SPECIES = ['mänd', 'kuusk', 'kask', 'haab', 'sanglepp', 'tamm', 'hall lepp', 'pihlakas']
const LOGGING_TYPES = [
  { code: 'U' },
  { code: 'L' },
  { code: 'H' },
  { code: 'T' },
  { code: 'R' },
]

function makeRichText(text: string): unknown {
  return {
    root: {
      children: [
        {
          type: 'paragraph',
          children: [{ text }],
        },
      ],
    },
  }
}

function futureDate(days: number, hours = 0, minutes = 0): Date {
  const d = new Date()
  d.setDate(d.getDate() + days)
  d.setHours(d.getHours() + hours)
  d.setMinutes(d.getMinutes() + minutes)
  return d
}

function pastDate(daysAgo: number, hours = 0): Date {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  d.setHours(d.getHours() - hours)
  return d
}

interface AuctionSeed {
  title: string
  slug: string
  status: string
  objectType: string
  isQuickAuction: boolean
  countyIndex: number
  parishIndex: number
  specialistIndex: number
  sellerIndex: number
  minBid: number
  reservePrice: number | undefined
  bidStep: number
  species: string[]
  loggingTypes: { code: string }[]
  endYear: number | undefined
  startsAt: Date | undefined
  endsAt: Date | undefined
  scheduledAt: Date | undefined
  activatedAt: Date | undefined
  endedAt: Date | undefined
  completedAt: Date | undefined
  archivedAt: Date | undefined
  contractAt: Date | undefined
  address: string
  packageHeader: string | undefined
  packageRows: unknown | undefined
  packageColumns: string[] | undefined
  descriptionPublic: unknown
}

const COUNTY_CODES = ['HH', 'TA', 'PR', 'VO', 'LV', 'SR', 'RA', 'IV', 'JG', 'PL']
const PARISH_NAMES_BY_COUNTY: Record<string, string[]> = {
  HH: ['Anija', 'Kose', 'Kuusalu', 'Raasiku', 'Rae', 'Saku', 'Viimsi'],
  TA: ['Elva', 'Kambja', 'Kastre', 'Luunja', 'Nõo', 'Tartu'],
  PR: ['Häädemeeste', 'Põhja-Pärnumaa', 'Saarde', 'Tori'],
  VO: ['Antsla', 'Rõuge', 'Võru', 'Võru vald'],
  LV: ['Haljala', 'Rakvere', 'Vinni', 'Väike-Maarja'],
  SR: ['Saaremaa', 'Muhu'],
  RA: ['Kehtna', 'Rapla', 'Märjamaa'],
  IV: ['Alutaguse', 'Jõhvi', 'Toila'],
  JG: ['Jõgeva', 'Põltsamaa'],
  PL: ['Kanepi', 'Põlva', 'Räpina'],
}

const AUCTIONS: AuctionSeed[] = [
  // ── DRAFT (2) ──
  {
    title: 'Raieõigus – Kose metsatükk',
    slug: 'raieoigus-kose',
    status: 'draft',
    objectType: 'raieoigus',
    isQuickAuction: false,
    countyIndex: 0,
    parishIndex: 0,
    specialistIndex: 0,
    sellerIndex: 0,
    minBid: 2500,
    reservePrice: 3000,
    bidStep: 200,
    species: ['mänd', 'kuusk'],
    loggingTypes: [{ code: 'U' }, { code: 'L' }],
    endYear: 2026,
    startsAt: undefined,
    endsAt: undefined,
    scheduledAt: undefined,
    activatedAt: undefined,
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Kose vald, Harjumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Raieõigus Kose metsatükile. Mänd ja kuusk, umbes 3 ha.'),
  },
  {
    title: 'Kinnistu – Tartu maaüksus',
    slug: 'kinnistu-tartu',
    status: 'draft',
    objectType: 'kinnistu',
    isQuickAuction: true,
    countyIndex: 1,
    parishIndex: 1,
    specialistIndex: 1,
    sellerIndex: 1,
    minBid: 45000,
    reservePrice: 50000,
    bidStep: 2000,
    species: [],
    loggingTypes: [],
    endYear: undefined,
    startsAt: undefined,
    endsAt: undefined,
    scheduledAt: undefined,
    activatedAt: undefined,
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Kambja vald, Tartumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Maaüksus Kambja vallas.'),
  },

  // ── SCHEDULED (3) ──
  {
    title: 'Kiire raieõigus – Saaremaa rannik',
    slug: 'kiire-saaremaa',
    status: 'scheduled',
    objectType: 'kiire',
    isQuickAuction: true,
    countyIndex: 5,
    parishIndex: 0,
    specialistIndex: 2,
    sellerIndex: 2,
    minBid: 500,
    reservePrice: undefined,
    bidStep: 50,
    species: ['mänd'],
    loggingTypes: [{ code: 'H' }],
    endYear: 2026,
    startsAt: futureDate(10),
    endsAt: futureDate(17),
    scheduledAt: futureDate(10),
    activatedAt: undefined,
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Saaremaa vald, Saaremaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Kiire raieõigus Saaremaa rannikualal.'),
  },
  {
    title: 'Raieõigus – Põlvamaa mets',
    slug: 'raieoigus-polva',
    status: 'scheduled',
    objectType: 'raieoigus',
    isQuickAuction: false,
    countyIndex: 9,
    parishIndex: 0,
    specialistIndex: 3,
    sellerIndex: 1,
    minBid: 5000,
    reservePrice: 6000,
    bidStep: 500,
    species: ['kuusk', 'kask', 'haab'],
    loggingTypes: [{ code: 'U' }],
    endYear: 2027,
    startsAt: futureDate(14),
    endsAt: futureDate(21),
    scheduledAt: futureDate(14),
    activatedAt: undefined,
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Kanepi vald, Põlvamaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Raieõigus Kanepi valla metsatükile.'),
  },
  {
    title: 'Kinnistu – Lääne-Viru põllumaa',
    slug: 'kinnistu-laaneviru',
    status: 'scheduled',
    objectType: 'kinnistu',
    isQuickAuction: false,
    countyIndex: 4,
    parishIndex: 0,
    specialistIndex: 4,
    sellerIndex: 0,
    minBid: 35000,
    reservePrice: 40000,
    bidStep: 1000,
    species: [],
    loggingTypes: [],
    endYear: undefined,
    startsAt: futureDate(20),
    endsAt: futureDate(30),
    scheduledAt: futureDate(20),
    activatedAt: undefined,
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Haljala vald, Lääne-Virumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Põllumajandusmaa Haljala vallas.'),
  },

  // ── ACTIVE (6) ──
  {
    title: 'Raieõigus – Rae valla mets',
    slug: 'raieoigus-rae',
    status: 'active',
    objectType: 'raieoigus',
    isQuickAuction: false,
    countyIndex: 0,
    parishIndex: 0,
    specialistIndex: 0,
    sellerIndex: 0,
    minBid: 3200,
    reservePrice: 4000,
    bidStep: 300,
    species: ['mänd', 'kuusk', 'kask'],
    loggingTypes: [{ code: 'U' }, { code: 'L' }],
    endYear: 2026,
    startsAt: pastDate(1),
    endsAt: futureDate(5),
    scheduledAt: pastDate(1),
    activatedAt: pastDate(1),
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Rae vald, Harjumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Raieõigus Rae valla metsakinnistul.'),
  },
  {
    title: 'Kinnistu – Elva järveäärne',
    slug: 'kinnistu-elva',
    status: 'active',
    objectType: 'kinnistu',
    isQuickAuction: false,
    countyIndex: 1,
    parishIndex: 0,
    specialistIndex: 1,
    sellerIndex: 2,
    minBid: 28000,
    reservePrice: undefined,
    bidStep: 500,
    species: [],
    loggingTypes: [],
    endYear: undefined,
    startsAt: pastDate(2),
    endsAt: futureDate(8),
    scheduledAt: pastDate(2),
    activatedAt: pastDate(2),
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Elva vald, Tartumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Järveäärne kinnistu Elva vallas.'),
  },
  {
    title: 'Kiire raieõigus – Pärnumaa',
    slug: 'kiire-parnu',
    status: 'active',
    objectType: 'kiire',
    isQuickAuction: true,
    countyIndex: 2,
    parishIndex: 0,
    specialistIndex: 2,
    sellerIndex: 1,
    minBid: 800,
    reservePrice: 1000,
    bidStep: 50,
    species: ['mänd', 'sanglepp'],
    loggingTypes: [{ code: 'H' }, { code: 'T' }],
    endYear: 2026,
    startsAt: pastDate(3),
    endsAt: futureDate(4),
    scheduledAt: pastDate(3),
    activatedAt: pastDate(3),
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Häädemeeste vald, Pärnumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Kiire raieõigus Häädemeeste vallas.'),
  },
  {
    title: 'Pakett – Võrumaa metsakombinatsioon',
    slug: 'pakett-voru',
    status: 'active',
    objectType: 'pakett',
    isQuickAuction: false,
    countyIndex: 3,
    parishIndex: 1,
    specialistIndex: 3,
    sellerIndex: 2,
    minBid: 12000,
    reservePrice: 15000,
    bidStep: 1000,
    species: ['kuusk', 'kask', 'haab', 'tamm'],
    loggingTypes: [{ code: 'U' }, { code: 'R' }],
    endYear: 2027,
    startsAt: pastDate(1),
    endsAt: futureDate(6),
    scheduledAt: pastDate(1),
    activatedAt: pastDate(1),
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Rõuge vald, Võrumaa',
    packageHeader: 'Võrumaa metsakombinatsioon',
    packageRows: [
      { quarter: 'A1', area: 2.5, species: 'kuusk', volume: 120 },
      { quarter: 'B3', area: 1.8, species: 'kask', volume: 80 },
      { quarter: 'C2', area: 3.2, species: 'haab', volume: 60 },
    ],
    packageColumns: ['Kvartal', 'Pindala', 'Puuliik', 'Maht'],
    descriptionPublic: makeRichText('Metsakombinatsioon Rõuge vallas.'),
  },
  {
    title: 'Raieõigus – Rapla segamets',
    slug: 'raieoigus-rapla',
    status: 'active',
    objectType: 'raieoigus',
    isQuickAuction: false,
    countyIndex: 6,
    parishIndex: 1,
    specialistIndex: 0,
    sellerIndex: 0,
    minBid: 4200,
    reservePrice: 5000,
    bidStep: 400,
    species: ['mänd', 'kuusk', 'kask', 'sanglepp'],
    loggingTypes: [{ code: 'U' }, { code: 'L' }, { code: 'H' }],
    endYear: 2026,
    startsAt: pastDate(4),
    endsAt: futureDate(3),
    scheduledAt: pastDate(4),
    activatedAt: pastDate(4),
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Rapla vald, Raplamaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Raieõigus Rapla valla segametsale.'),
  },
  {
    title: 'Kinnistu – Ida-Viru metsamaa',
    slug: 'kinnistu-ida-viru',
    status: 'active',
    objectType: 'kinnistu',
    isQuickAuction: false,
    countyIndex: 7,
    parishIndex: 0,
    specialistIndex: 4,
    sellerIndex: 1,
    minBid: 22000,
    reservePrice: undefined,
    bidStep: 1000,
    species: [],
    loggingTypes: [],
    endYear: undefined,
    startsAt: pastDate(1),
    endsAt: futureDate(10),
    scheduledAt: pastDate(1),
    activatedAt: pastDate(1),
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Alutaguse vald, Ida-Virumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Metsamaa Alutaguse vallas.'),
  },

  // ── ENDING SOON (2, endTime within 5 min) ──
  {
    title: 'Kiire raieõigus – Jõgevamaa',
    slug: 'kiire-jogeva-ending',
    status: 'active',
    objectType: 'kiire',
    isQuickAuction: true,
    countyIndex: 8,
    parishIndex: 0,
    specialistIndex: 2,
    sellerIndex: 2,
    minBid: 600,
    reservePrice: undefined,
    bidStep: 50,
    species: ['kask', 'haab'],
    loggingTypes: [{ code: 'H' }],
    endYear: 2026,
    startsAt: pastDate(5),
    endsAt: futureDate(0, 0, 3),
    scheduledAt: pastDate(5),
    activatedAt: pastDate(5),
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Jõgeva vald, Jõgevamaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Kiire raieõigus – lõppemas!'),
  },
  {
    title: 'Raieõigus – Viljandi metsatükk',
    slug: 'raieoigus-viljandi-ending',
    status: 'active',
    objectType: 'raieoigus',
    isQuickAuction: false,
    countyIndex: 0,
    parishIndex: 0,
    specialistIndex: 3,
    sellerIndex: 0,
    minBid: 3800,
    reservePrice: 4500,
    bidStep: 300,
    species: ['mänd', 'kuusk', 'kask', 'pihlakas'],
    loggingTypes: [{ code: 'U' }, { code: 'L' }],
    endYear: 2026,
    startsAt: pastDate(5),
    endsAt: futureDate(0, 0, 1),
    scheduledAt: pastDate(5),
    activatedAt: pastDate(5),
    endedAt: undefined,
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Viljandi lähistel',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Raieõigus – viimased hetked!'),
  },

  // ── ENDED (5) ──
  {
    title: 'Raieõigus – Saku mets',
    slug: 'raieoigus-saku-ended',
    status: 'ended',
    objectType: 'raieoigus',
    isQuickAuction: false,
    countyIndex: 0,
    parishIndex: 0,
    specialistIndex: 0,
    sellerIndex: 1,
    minBid: 2800,
    reservePrice: 3500,
    bidStep: 200,
    species: ['mänd', 'kuusk'],
    loggingTypes: [{ code: 'U' }],
    endYear: 2026,
    startsAt: pastDate(10),
    endsAt: pastDate(3),
    scheduledAt: pastDate(10),
    activatedAt: pastDate(10),
    endedAt: pastDate(3),
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Saku vald, Harjumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Raieõigus Saku vallas – lõppenud.'),
  },
  {
    title: 'Kinnistu – Muhu maaüksus',
    slug: 'kinnistu-muhu-ended',
    status: 'ended',
    objectType: 'kinnistu',
    isQuickAuction: false,
    countyIndex: 5,
    parishIndex: 1,
    specialistIndex: 1,
    sellerIndex: 2,
    minBid: 18000,
    reservePrice: undefined,
    bidStep: 500,
    species: [],
    loggingTypes: [],
    endYear: undefined,
    startsAt: pastDate(15),
    endsAt: pastDate(8),
    scheduledAt: pastDate(15),
    activatedAt: pastDate(15),
    endedAt: pastDate(8),
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Muhu vald, Saaremaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Maaüksus Muhu saarel – lõppenud.'),
  },
  {
    title: 'Kiire raieõigus – Kehtna',
    slug: 'kiire-kehtna-ended',
    status: 'ended',
    objectType: 'kiire',
    isQuickAuction: true,
    countyIndex: 6,
    parishIndex: 0,
    specialistIndex: 2,
    sellerIndex: 0,
    minBid: 700,
    reservePrice: 900,
    bidStep: 50,
    species: ['sanglepp', 'hall lepp'],
    loggingTypes: [{ code: 'H' }, { code: 'T' }],
    endYear: 2026,
    startsAt: pastDate(8),
    endsAt: pastDate(1),
    scheduledAt: pastDate(8),
    activatedAt: pastDate(8),
    endedAt: pastDate(1),
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Kehtna vald, Raplamaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Kiire raieõigus Kehtna vallas – lõppenud.'),
  },
  {
    title: 'Raieõigus – Võru mets',
    slug: 'raieoigus-voru-ended',
    status: 'ended',
    objectType: 'raieoigus',
    isQuickAuction: false,
    countyIndex: 3,
    parishIndex: 1,
    specialistIndex: 3,
    sellerIndex: 1,
    minBid: 5500,
    reservePrice: 7000,
    bidStep: 500,
    species: ['kuusk', 'kask', 'haab', 'tamm'],
    loggingTypes: [{ code: 'U' }, { code: 'L' }, { code: 'R' }],
    endYear: 2026,
    startsAt: pastDate(12),
    endsAt: pastDate(4),
    scheduledAt: pastDate(12),
    activatedAt: pastDate(12),
    endedAt: pastDate(4),
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Rõuge vald, Võrumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Raieõigus Rõuge vallas – lõppenud.'),
  },
  {
    title: 'Pakett – Ida-Viru',
    slug: 'pakett-ida-viru-ended',
    status: 'ended',
    objectType: 'pakett',
    isQuickAuction: false,
    countyIndex: 7,
    parishIndex: 1,
    specialistIndex: 4,
    sellerIndex: 2,
    minBid: 9500,
    reservePrice: 12000,
    bidStep: 500,
    species: ['mänd', 'kuusk'],
    loggingTypes: [{ code: 'U' }],
    endYear: 2027,
    startsAt: pastDate(14),
    endsAt: pastDate(5),
    scheduledAt: pastDate(14),
    activatedAt: pastDate(14),
    endedAt: pastDate(5),
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Toila vald, Ida-Virumaa',
    packageHeader: 'Ida-Viru pakett',
    packageRows: [
      { row: '1', area_ha: 4.2 },
      { row: '2', area_ha: 3.1 },
      { row: '3', area_ha: 2.8 },
    ],
    packageColumns: ['Rida', 'Pindala (ha)'],
    descriptionPublic: makeRichText('Pakettmets Ida-Virumaal – lõppenud.'),
  },

  // ── SOLD (4, status=completed) ──
  {
    title: 'Raieõigus – Viimsi mets',
    slug: 'raieoigus-viimsi-sold',
    status: 'completed',
    objectType: 'raieoigus',
    isQuickAuction: false,
    countyIndex: 0,
    parishIndex: 0,
    specialistIndex: 0,
    sellerIndex: 0,
    minBid: 4200,
    reservePrice: 5000,
    bidStep: 400,
    species: ['mänd', 'kuusk', 'kask'],
    loggingTypes: [{ code: 'U' }, { code: 'L' }],
    endYear: 2025,
    startsAt: pastDate(60),
    endsAt: pastDate(53),
    scheduledAt: pastDate(60),
    activatedAt: pastDate(60),
    endedAt: pastDate(53),
    completedAt: pastDate(48),
    archivedAt: undefined,
    contractAt: pastDate(48),
    address: 'Viimsi vald, Harjumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Raieõigus Viimsi vallas – müüdud.'),
  },
  {
    title: 'Kinnistu – Türi',
    slug: 'kinnistu-tyri-sold',
    status: 'completed',
    objectType: 'kinnistu',
    isQuickAuction: false,
    countyIndex: 1,
    parishIndex: 1,
    specialistIndex: 1,
    sellerIndex: 1,
    minBid: 15000,
    reservePrice: 18000,
    bidStep: 1000,
    species: [],
    loggingTypes: [],
    endYear: undefined,
    startsAt: pastDate(50),
    endsAt: pastDate(43),
    scheduledAt: pastDate(50),
    activatedAt: pastDate(50),
    endedAt: pastDate(43),
    completedAt: pastDate(38),
    archivedAt: undefined,
    contractAt: pastDate(38),
    address: 'Kambja vald, Tartumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Maaüksus – müüdud.'),
  },
  {
    title: 'Kiire raieõigus – Pärnu rand',
    slug: 'kiire-parnu-sold',
    status: 'completed',
    objectType: 'kiire',
    isQuickAuction: true,
    countyIndex: 2,
    parishIndex: 0,
    specialistIndex: 2,
    sellerIndex: 2,
    minBid: 400,
    reservePrice: undefined,
    bidStep: 50,
    species: ['sanglepp'],
    loggingTypes: [{ code: 'H' }],
    endYear: 2025,
    startsAt: pastDate(45),
    endsAt: pastDate(38),
    scheduledAt: pastDate(45),
    activatedAt: pastDate(45),
    endedAt: pastDate(38),
    completedAt: pastDate(33),
    archivedAt: undefined,
    contractAt: pastDate(33),
    address: 'Tori vald, Pärnumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Kiire raieõigus – müüdud.'),
  },
  {
    title: 'Pakett – Lääne-Viru',
    slug: 'pakett-laaneviru-sold',
    status: 'completed',
    objectType: 'pakett',
    isQuickAuction: false,
    countyIndex: 4,
    parishIndex: 1,
    specialistIndex: 4,
    sellerIndex: 0,
    minBid: 8500,
    reservePrice: 10000,
    bidStep: 500,
    species: ['kuusk', 'kask'],
    loggingTypes: [{ code: 'U' }],
    endYear: 2026,
    startsAt: pastDate(40),
    endsAt: pastDate(33),
    scheduledAt: pastDate(40),
    activatedAt: pastDate(40),
    endedAt: pastDate(33),
    completedAt: pastDate(28),
    archivedAt: undefined,
    contractAt: pastDate(28),
    address: 'Rakvere vald, Lääne-Virumaa',
    packageHeader: 'Lääne-Viru pakett',
    packageRows: [
      { lot: 'A', size: 3.5 },
      { lot: 'B', size: 2.1 },
      { lot: 'C', size: 4.0 },
    ],
    packageColumns: ['Partii', 'Suurus (ha)'],
    descriptionPublic: makeRichText('Pakett Lääne-Virumaal – müüdud.'),
  },

  // ── UNSOLD (4, status=unsold) ──
  {
    title: 'Raieõigus – Kuusalu',
    slug: 'raieoigus-kuusalu-unsold',
    status: 'unsold',
    objectType: 'raieoigus',
    isQuickAuction: false,
    countyIndex: 0,
    parishIndex: 0,
    specialistIndex: 0,
    sellerIndex: 2,
    minBid: 6500,
    reservePrice: 8000,
    bidStep: 500,
    species: ['kuusk', 'kask', 'haab'],
    loggingTypes: [{ code: 'U' }],
    endYear: 2025,
    startsAt: pastDate(70),
    endsAt: pastDate(63),
    scheduledAt: pastDate(70),
    activatedAt: pastDate(70),
    endedAt: pastDate(63),
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Kuusalu vald, Harjumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Raieõigus Kuusalu vallas – müümata.'),
  },
  {
    title: 'Kinnistu – Põlva',
    slug: 'kinnistu-polva-unsold',
    status: 'unsold',
    objectType: 'kinnistu',
    isQuickAuction: false,
    countyIndex: 9,
    parishIndex: 1,
    specialistIndex: 1,
    sellerIndex: 0,
    minBid: 20000,
    reservePrice: 25000,
    bidStep: 1000,
    species: [],
    loggingTypes: [],
    endYear: undefined,
    startsAt: pastDate(65),
    endsAt: pastDate(58),
    scheduledAt: pastDate(65),
    activatedAt: pastDate(65),
    endedAt: pastDate(58),
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Põlva vald, Põlvamaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Maaüksus Põlva vallas – müümata.'),
  },
  {
    title: 'Kiire raieõigus – Jõhvi',
    slug: 'kiire-johvi-unsold',
    status: 'unsold',
    objectType: 'kiire',
    isQuickAuction: true,
    countyIndex: 7,
    parishIndex: 1,
    specialistIndex: 2,
    sellerIndex: 1,
    minBid: 1000,
    reservePrice: 1200,
    bidStep: 100,
    species: ['mänd', 'kask'],
    loggingTypes: [{ code: 'H' }],
    endYear: 2025,
    startsAt: pastDate(55),
    endsAt: pastDate(48),
    scheduledAt: pastDate(55),
    activatedAt: pastDate(55),
    endedAt: pastDate(48),
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Jõhvi vald, Ida-Virumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Kiire raieõigus – müümata.'),
  },
  {
    title: 'Raieõigus – Lääneranna',
    slug: 'raieoigus-laane-unsold',
    status: 'unsold',
    objectType: 'raieoigus',
    isQuickAuction: false,
    countyIndex: 2,
    parishIndex: 1,
    specialistIndex: 3,
    sellerIndex: 2,
    minBid: 3000,
    reservePrice: 4000,
    bidStep: 300,
    species: ['haab', 'sanglepp', 'hall lepp'],
    loggingTypes: [{ code: 'U' }, { code: 'H' }],
    endYear: 2025,
    startsAt: pastDate(75),
    endsAt: pastDate(68),
    scheduledAt: pastDate(75),
    activatedAt: pastDate(75),
    endedAt: pastDate(68),
    completedAt: undefined,
    archivedAt: undefined,
    contractAt: undefined,
    address: 'Lääneranna vald, Pärnumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Raieõigus Lääneranna vallas – müümata.'),
  },

  // ── ARCHIVED (4) ──
  {
    title: 'Raieõigus – Anija',
    slug: 'raieoigus-anija-archived',
    status: 'archived',
    objectType: 'raieoigus',
    isQuickAuction: false,
    countyIndex: 0,
    parishIndex: 0,
    specialistIndex: 0,
    sellerIndex: 0,
    minBid: 2200,
    reservePrice: 2800,
    bidStep: 200,
    species: ['mänd', 'kask'],
    loggingTypes: [{ code: 'U' }],
    endYear: 2025,
    startsAt: pastDate(150),
    endsAt: pastDate(143),
    scheduledAt: pastDate(150),
    activatedAt: pastDate(150),
    endedAt: pastDate(143),
    completedAt: undefined,
    archivedAt: pastDate(130),
    contractAt: undefined,
    address: 'Anija vald, Harjumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Raieõigus Anija vallas – arhiveeritud.'),
  },
  {
    title: 'Kinnistu – Saaremaa',
    slug: 'kinnistu-saaremaa-archived',
    status: 'archived',
    objectType: 'kinnistu',
    isQuickAuction: false,
    countyIndex: 5,
    parishIndex: 0,
    specialistIndex: 1,
    sellerIndex: 1,
    minBid: 12000,
    reservePrice: undefined,
    bidStep: 1000,
    species: [],
    loggingTypes: [],
    endYear: undefined,
    startsAt: pastDate(120),
    endsAt: pastDate(113),
    scheduledAt: pastDate(120),
    activatedAt: pastDate(120),
    endedAt: pastDate(113),
    completedAt: undefined,
    archivedAt: pastDate(100),
    contractAt: undefined,
    address: 'Saaremaa vald, Saaremaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Maaüksus Saaremaal – arhiveeritud.'),
  },
  {
    title: 'Kiire raieõigus – Võru kiirpakett',
    slug: 'kiire-voru-archived',
    status: 'archived',
    objectType: 'kiire',
    isQuickAuction: true,
    countyIndex: 3,
    parishIndex: 0,
    specialistIndex: 2,
    sellerIndex: 2,
    minBid: 900,
    reservePrice: undefined,
    bidStep: 100,
    species: ['kuusk', 'kask'],
    loggingTypes: [{ code: 'H' }],
    endYear: 2025,
    startsAt: pastDate(90),
    endsAt: pastDate(83),
    scheduledAt: pastDate(90),
    activatedAt: pastDate(90),
    endedAt: pastDate(83),
    completedAt: undefined,
    archivedAt: pastDate(70),
    contractAt: undefined,
    address: 'Antsla vald, Võrumaa',
    packageHeader: undefined,
    packageRows: undefined,
    packageColumns: undefined,
    descriptionPublic: makeRichText('Kiire raieõigus – arhiveeritud.'),
  },
  {
    title: 'Pakett – Jõgeva arhiiv',
    slug: 'pakett-jogeva-archived',
    status: 'archived',
    objectType: 'pakett',
    isQuickAuction: false,
    countyIndex: 8,
    parishIndex: 1,
    specialistIndex: 4,
    sellerIndex: 0,
    minBid: 7500,
    reservePrice: 9000,
    bidStep: 500,
    species: ['kuusk', 'kask', 'haab'],
    loggingTypes: [{ code: 'U' }],
    endYear: 2024,
    startsAt: pastDate(200),
    endsAt: pastDate(193),
    scheduledAt: pastDate(200),
    activatedAt: pastDate(200),
    endedAt: pastDate(193),
    completedAt: undefined,
    archivedAt: pastDate(180),
    contractAt: undefined,
    address: 'Põltsamaa vald, Jõgevamaa',
    packageHeader: 'Jõgeva pakett (arhiveeritud)',
    packageRows: [
      { item: 'Metsatükk 1', ha: 5.0 },
      { item: 'Metsatükk 2', ha: 3.3 },
      { item: 'Metsatükk 3', ha: 4.7 },
    ],
    packageColumns: ['Kirjeldus', 'Pindala (ha)'],
    descriptionPublic: makeRichText('Pakett Jõgevamaal – arhiveeritud.'),
  },
]

export async function seedAuctions(payload: Payload): Promise<void> {
  const existing = await payload.find({ collection: 'auctions', limit: 1 })
  if (existing.totalDocs > 0) {
    console.log('Auctions already seeded, skipping')
    return
  }

  const { docs: counties } = await payload.find({ collection: 'counties', limit: 15 })
  const { docs: parishes } = await payload.find({ collection: 'parishes', limit: 60 })
  const { docs: specialists } = await payload.find({ collection: 'specialist', limit: 10 })
  const { docs: users } = await payload.find({ collection: 'users', limit: 15 })

  if (counties.length === 0) throw new Error('No counties found. Run seedTaxonomies first.')
  if (specialists.length === 0) throw new Error('No specialists found. Run seedSpecialists first.')
  if (users.length === 0) throw new Error('No users found. Run seedUsers first.')

  const countyByCode = new Map(counties.map((c) => [c.code as string, c]))
  const parishByNameAndCounty = new Map<string, string>()
  for (const p of parishes) {
    const countyId = (p.county as { id: string })?.id
    if (countyId) {
      parishByNameAndCounty.set(`${p.name as string}|${countyId}`, p.id as string)
    }
  }

  let created = 0
  for (const a of AUCTIONS) {
    const countyCode = COUNTY_CODES[a.countyIndex]
    if (!countyCode) {
      console.warn(`Skipping "${a.title}": no county code at index ${a.countyIndex}`)
      continue
    }

    const county = countyByCode.get(countyCode)
    if (!county) {
      console.warn(`Skipping "${a.title}": county code ${countyCode} not found in DB`)
      continue
    }

    const countyParishes = PARISH_NAMES_BY_COUNTY[countyCode]
    if (!countyParishes) {
      console.warn(`Skipping "${a.title}": unknown county ${countyCode}`)
      continue
    }

    const parishName = countyParishes[a.parishIndex]
    if (!parishName) {
      console.warn(`Skipping "${a.title}": no parish at index ${a.parishIndex} for ${countyCode}`)
      continue
    }

    const parishId = parishByNameAndCounty.get(`${parishName}|${county.id}`)
    if (!parishId) {
      console.warn(`Skipping "${a.title}": parish ${parishName} not found for county ${countyCode}`)
      continue
    }

    const specialist = specialists[a.specialistIndex % specialists.length]
    if (!specialist) {
      console.warn(`Skipping "${a.title}": specialist at index ${a.specialistIndex} not found`)
      continue
    }

    const seller = users[3 + (a.sellerIndex % (users.length - 3))]
    if (!seller) {
      console.warn(`Skipping "${a.title}": seller at index ${a.sellerIndex} not found`)
      continue
    }

    await payload.create({
      collection: 'auctions',
      data: {
        title: a.title,
        slug: a.slug,
        status: a.status,
        objectType: a.objectType,
        isQuickAuction: a.isQuickAuction,
        endYear: a.endYear,
        county: county.id,
        parish: parishId,
        address: a.address,
        species: a.species,
        loggingTypes: a.loggingTypes,
        minBid: a.minBid,
        reservePrice: a.reservePrice,
        bidStep: a.bidStep,
        vatIncluded: true,
        specialist: specialist.id,
        seller: seller.id,
        startsAt: a.startsAt,
        endsAt: a.endsAt,
        scheduledAt: a.scheduledAt,
        activatedAt: a.activatedAt,
        endedAt: a.endedAt,
        completedAt: a.completedAt,
        archivedAt: a.archivedAt,
        contractAt: a.contractAt,
        packageHeader: a.packageHeader,
        packageRows: a.packageRows,
        packageColumns: a.packageColumns?.map((c) => ({ column: c })),
        descriptionPublic: a.descriptionPublic,
      },
    })
    created++
  }

  console.log(`Seeded ${created} demo auctions`)
}
